---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family | lower == "debian"
    - name: Install ssh.
      ansible.builtin.package:
        name: openssh{{ (ansible_os_family | lower == "debian") | ternary("-client", "") }}
        state: present
